### ISSUE TITLE
Postgrest ingress.hosts.paths should be paths: [/] instead of paths: []

### ISSUE THREAD

**Issue by yevon** [colearendt/helm#30]
I think that ingress.hosts.paths in default values.yaml should be paths: [/] instead of paths: []

If not, I was getting error messages.

**Comment by colearendt** [comment]
Yeah, that makes sense. Right now the default values force you to set it. However, the downside of setting a default is I need to be sure whether it is tricky at all to unset the value for someone who doesn't like the value (I think `paths: []` would just append, but maybe `paths: null` would work).

In any case, thanks for reporting! I will take a look!
