### ISSUE TITLE
Support for kubernetes 1.22+ for postgrest chart, ingress template networking.k8s.io/v1beta1 deprecated

### ISSUE THREAD

**Issue by yevon** [colearendt/helm#39]
Hi! It seems that the use of networking.k8s.io/v1beta1 has been completely deleted in kubernetes 1.22+. Could you please change the chart template for postgrest by changing networking.k8s.io/v1beta1 for **networking.k8s.io/v1**?

You might find this useful:

https://github.com/Place1/wg-access-server/issues/146

**Comment by colearendt** [comment]
Thanks for reporting! I definitely can - unfortunately a bit delayed on catching up on that!

Sent from my iPhone

On Apr 26, 2022, at 5:42 PM, Gabriel ***@***.***> wrote:

﻿

Hi! It seems that the use of networking.k8s.io/v1beta1 has been completely deleted in kubernetes 1.22+. Could you please change the chart template for postgrest by changing networking.k8s.io/v1beta1 for networking.k8s.io/v1?

You might find this useful:

Place1/wg-access-server#146<https://github.com/Place1/wg-access-server/issues/146>
